/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  primary: [
    {
      type: "category",
      label: "Getting started",
      items: ["introduction", "bidding"],
    },
    {
      type: "category",
      label: "API & SDKs",
      items: [
        "api/sdks",
        "api/authentication",
        "api/placements",
        // "api/only/categories",
        // "api/only/slots",
        // "api/only/advertiser",
        // "api/only/advertisements",
        // "api/only/transactions",
      ],
    },
    {
      type: "category",
      label: "Tracking",
      items: ["tracking/clicks", "tracking/views"],
    },
    {
      type: "category",
      label: "Webhooks",
      items: ["webhooks/promotables"],
    },
  ],
};

module.exports = sidebars;
